name: pyeo_env
channels:
  - conda-forge
dependencies:
  - boto3
  - botocore
  - gdal=2.4.3
  - joblib
  - matplotlib
  - pip
  - pytest
  - python
  - requests
  - scikit-image
  - setuptools
  - numpy
  - scikit-learn
  - scipy
  - python-fmask
  - beautifulsoup4
  - pip:
    - geojson
    - google-cloud
    - sentinelhub
    - sentinelsat
    - tenacity
    - tqdm
